apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooknco-mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cooknco-mail-service
  template:
    metadata:
      labels:
        app: cooknco-mail-service
    spec:
      containers:
        - name: mail-service
          image: xavierclavel/cooknco-mail-service:1.0.0
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/mail-service.jar"]          
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mail-database-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-database-secrets
                  key: postgres_password
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: mail-database-secrets
                  key: jdbc_url
          envFrom:
            - secretKeyRef:
                name: cooknco-secrets
          envFrom:
            - configMapRef:
                name: smtp-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
